-- BOAT RACE Prediction Cloud v5
-- Supabase SQL Editor でそのまま実行してください。

create extension if not exists pgcrypto;

create table if not exists public.race_snapshots (
  id uuid primary key default gen_random_uuid(),
  race_id text not null,
  snapshot_at timestamptz not null default now(),
  race_date date not null,
  stadium_code integer not null,
  stadium_name text not null,
  race_no integer not null,
  model_kind text,
  data_quality double precision,
  simulation_count integer,
  simulation_weight double precision,
  reliability double precision,
  weather jsonb,
  boats jsonb not null,
  result_json jsonb,
  settled boolean not null default false
);

create index if not exists race_snapshots_race_id_idx on public.race_snapshots(race_id);
create index if not exists race_snapshots_settled_idx on public.race_snapshots(settled, race_date);

create table if not exists public.ticket_predictions (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null references public.race_snapshots(id) on delete cascade,
  bet_type text not null,
  combo text not null,
  odds double precision,
  model_prob double precision,
  analytic_prob double precision,
  sim_prob double precision,
  market_prob_proxy double precision,
  conservative_prob double precision,
  conservative_ev double precision,
  consensus_class text,
  result_hit boolean,
  payoff integer
);

create index if not exists ticket_predictions_snapshot_idx on public.ticket_predictions(snapshot_id);

create table if not exists public.model_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  accepted boolean not null,
  note text,
  metrics jsonb
);

-- V5はStreamlitサーバー側の Supabase Secret Key を使う前提です。
-- Secret Key はRLSを迂回するため、GitHubには絶対に保存せず、Streamlit Secretsにだけ置いてください。
alter table public.race_snapshots enable row level security;
alter table public.ticket_predictions enable row level security;
alter table public.model_runs enable row level security;

-- Secret Key は service_role として動作します。明示的に権限を付与します。
grant all on table public.race_snapshots to service_role;
grant all on table public.ticket_predictions to service_role;
grant all on table public.model_runs to service_role;
grant usage, select on all sequences in schema public to service_role;

-- ---- V5: historical backfill / walk-forward jobs ---------------------------
alter table public.race_snapshots add column if not exists feature_weights jsonb not null default '{}'::jsonb;
alter table public.race_snapshots add column if not exists manual_weight_mix double precision not null default 0.30;
alter table public.race_snapshots add column if not exists source text not null default 'live';
alter table public.race_snapshots add column if not exists backtest_job_id uuid;
create index if not exists race_snapshots_backtest_idx on public.race_snapshots(backtest_job_id, race_id);

create table if not exists public.backtest_jobs (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  status text not null default 'queued',
  start_date date not null,
  end_date date not null,
  stadium_codes jsonb not null,
  bet_types jsonb not null,
  include_before boolean not null default true,
  include_odds boolean not null default true,
  simulation_count integer not null default 2000,
  simulation_weight double precision not null default 0.35,
  uncertainty_scale double precision not null default 1.0,
  feature_weights jsonb not null default '{}'::jsonb,
  manual_weight_mix double precision not null default 0.30,
  retrain_every integer not null default 50,
  max_races integer not null default 500,
  total_targets integer not null default 0,
  processed integer not null default 0,
  succeeded integer not null default 0,
  failed integer not null default 0,
  message text
);

-- Safe migration if an earlier V5 draft already created backtest_jobs.
alter table public.backtest_jobs add column if not exists feature_weights jsonb not null default '{}'::jsonb;
alter table public.backtest_jobs add column if not exists manual_weight_mix double precision not null default 0.30;

create table if not exists public.backtest_queue (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.backtest_jobs(id) on delete cascade,
  race_date date not null,
  stadium_code integer not null,
  race_no integer not null,
  status text not null default 'pending',
  snapshot_id uuid references public.race_snapshots(id) on delete set null,
  error text,
  unique(job_id, race_date, stadium_code, race_no)
);

create index if not exists backtest_queue_job_status_idx on public.backtest_queue(job_id, status, race_date);

alter table public.backtest_jobs enable row level security;
alter table public.backtest_queue enable row level security;
grant all on table public.backtest_jobs to service_role;
grant all on table public.backtest_queue to service_role;
grant usage, select on all sequences in schema public to service_role;
