-- BOAT RACE Prediction Cloud v4
-- Supabase SQL Editor でそのまま実行してください。

create extension if not exists pgcrypto;

create table if not exists public.race_snapshots (
  id uuid primary key default gen_random_uuid(),
  race_id text not null,
  snapshot_at timestamptz not null default now(),
  race_date date not null,
  stadium_code integer not null,
  stadium_name text not null,
  race_no integer not null,
  model_kind text,
  data_quality double precision,
  simulation_count integer,
  simulation_weight double precision,
  reliability double precision,
  weather jsonb,
  boats jsonb not null,
  result_json jsonb,
  settled boolean not null default false
);

create index if not exists race_snapshots_race_id_idx on public.race_snapshots(race_id);
create index if not exists race_snapshots_settled_idx on public.race_snapshots(settled, race_date);

create table if not exists public.ticket_predictions (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null references public.race_snapshots(id) on delete cascade,
  bet_type text not null,
  combo text not null,
  odds double precision,
  model_prob double precision,
  analytic_prob double precision,
  sim_prob double precision,
  market_prob_proxy double precision,
  conservative_prob double precision,
  conservative_ev double precision,
  consensus_class text,
  result_hit boolean,
  payoff integer
);

create index if not exists ticket_predictions_snapshot_idx on public.ticket_predictions(snapshot_id);

create table if not exists public.model_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  accepted boolean not null,
  note text,
  metrics jsonb
);

-- V4はStreamlitサーバー側の Supabase Secret Key を使う前提です。
-- Secret Key はRLSを迂回するため、GitHubには絶対に保存せず、Streamlit Secretsにだけ置いてください。
alter table public.race_snapshots enable row level security;
alter table public.ticket_predictions enable row level security;
alter table public.model_runs enable row level security;

-- Secret Key は service_role として動作します。明示的に権限を付与します。
grant all on table public.race_snapshots to service_role;
grant all on table public.ticket_predictions to service_role;
grant all on table public.model_runs to service_role;
grant usage, select on all sequences in schema public to service_role;
